"""init models

Revision ID: 7b1b3001f720
Revises: 
Create Date: 2026-05-15 22:09:22.118196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1b3001f720'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.add_column('products', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('discountPrice', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('images', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('featured', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('specifications', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'createdAt')
    op.drop_column('products', 'specifications')
    op.drop_column('products', 'featured')
    op.drop_column('products', 'rating')
    op.drop_column('products', 'images')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'discountPrice')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'category')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
