"""add bank_slip_url to orders

Revision ID: 91806378371f
Revises: 590782437e11
Create Date: 2026-08-04 21:37:07.505981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91806378371f'
down_revision: Union[str, Sequence[str], None] = '590782437e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('bank_slip_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'bank_slip_url')
    # ### end Alembic commands ###
