"""add reviewCount

Revision ID: d5baf5ab5f92
Revises: 1db3941565b1
Create Date: 2026-08-07 20:23:38.650873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5baf5ab5f92'
down_revision: Union[str, Sequence[str], None] = '1db3941565b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('reviewCount', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('freeShipping', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'freeShipping')
    op.drop_column('products', 'reviewCount')
    # ### end Alembic commands ###
